config/routes.rb
Planet::Application.routes.draw do

  root :to => "planet#index"

  devise_for :users
  resources :users, :only => [:index, :show]

  resources :typecomentarios
  
  resources :comments

  resources :sites do
       collection do
          get 'search'
       end
   end

  resources :sites do
	member do
	get 'like'
	end
  end

  resources :respuesta do
	member do
	get 'like'
	end
  end

  resources :types do
      resources :sites
  end

  resources :sites do
      resources :comments
  end

  resources :comments do
      resources :respuesta
  end
  resources :sites
  resources :respuesta

  get "planet/index"
  get "planet/explorar"
  get "planet/contacto"
  get "planet/acercade"
  get "planet/terminos"
  get "planet/privacidad"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :site
	has_many :respuesta

   validates :nombre, :latitude, :longitude, :zoom, :comment, :site_id, :presence => true
   validates_uniqueness_of :nombre, :case_sensitive => false

	attr_protected :user_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  before_filter :authenticate_user!, :except => [ :index, :show, :search]
  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to(root_url, :notice => 'Permiso denegado.')
  end

  # GET /comments
  # GET /comments.xml
  def index

   if params[:site_id].nil? or params[:site_id].empty? and params[:estacion].nil?
      @comments = Comment.all
      @comments_turisticos = Comment.where(:esturistico => 1)
      @titulo = "Sitios"
    elsif !params[:estacion].nil? 
      @comments = Comment.where(:estacion => params[:estacion])
      @comments_turisticos = Comment.where(:estacion => params[:estacion], :esturistico => 1)
      @titulo = "Sitios ideales para ver en esta estacion"   
    elsif params[:tipocomentario].nil? or params[:tipocomentario].empty?
      @comments = Comment.where(:site_id => params[:site_id])
      @comments_turisticos = Comment.where(:tipocomentario => params[:tipocomentario], :site_id => params[:site_id], :esturistico => 1)
      @localidad = Site.find(params[:site_id]).name
    else
      @comments = Comment.where(:tipocomentario => params[:tipocomentario], :site_id => params[:site_id])
      @comments_turisticos = Comment.where(:tipocomentario => params[:tipocomentario], :site_id => params[:site_id], :esturistico => 1)
      @localidad = Site.find(params[:site_id]).name
      @tipo = params[:tipocomentario]

   end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])
    @user = User.find_by_id(@comment.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  # GET /sites/1/comments/new
  # GET /sites/1/comments/new.xml
  def new

   if params[:site_id] and params[:tipocomentario]
      @comment.site_id = params[:site_id]
      @comment.user = current_user
      @comment.tipocomentario = params[:tipocomentario]
   elsif params[:site_id]
      @comment.site_id = params[:site_id]
      @comment.user = current_user
    else
      @comment.user = current_user
   end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@comment, :notice => 'Nuevo sitio creado.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Sitio actualizado correctamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(site_comments_path(@comment.site_id)) }
      format.xml  { head :ok }
    end
  end

 def subekarma
     @comment = current_user.comments.find(params[:id])
     User.find(@comment.user_id).update_attribute(:karma, User.find(@comment.user_id).karma+1)
 end
end

app/helpers/comments_helper.rb
module CommentsHelper

 def tipocomentario(comment)
 	tipo = case comment.tipocomentario
	 	when 2 then "Sitios que hay que ver"
	 	when 3 then "Monumentos"
	 	when 4 then "Museos"
	 	when 5 then "Hoteles"
	 	when 6 then "Casas rurales"
	 	when 7 then "Sitios donde comer"
	 	when 8 then "De compras"
	 	when 9 then "Parques"
	 	when 10 then "Transporte"
	end

	return tipo
end
 def tipocomentarioconid(id)
 	tipo = case id.to_s
	 	when 2 then "Sitios que hay que ver"
	 	when 3 then "Monumentos"
	 	when 4 then "Museos"
	 	when 5 then "Hoteles"
	 	when 6 then "Casas rurales"
	 	when 7 then "Sitios donde comer"
	 	when 8 then "De compras"
	 	when 9 then "Parques"
	 	when 10 then "Transporte" 		
	end 
	return tipo
end

 def getestacion(comment)
 	tipo = case comment.estacion
	 	when 1 then "Cualquier epoca"
		when 2 then "Primavera"
		when 3 then "Verano"
		when 4 then "Otono"
		when 5 then "Invierno"
	end

	return tipo
end

end

app/views/comments/_form.html.erb
<body id="planet" onload="initialize()"> 
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id= "col1">
  ¿Qué tipo de información es?
  <div class="field">
<%= f.select(:tipocomentario, options_for_select([['Sitio que hay que ver', 2], ['Monumento', 3], ['Museo', 4], ['Hotel', 5], ['Casa Rural', 6], ['Sitio donde comer', 7], ['De compras', 8], ['Parques', 9], ['Transporte', 10]], @comment.tipocomentario), {:include_blank => false}, :class => 'styled-select')%>
  </div>
  <div class="field">
    Nombre del sitio:<br />
    <%= f.text_field :nombre, {:class=>"text-input", :maxlength=>"53"}  %>
  </div>
  <div class="field">
    Descripción u opinión:<br />
    <%= f.text_area :comment, :rows => 4  %>
  </div>
  <div class="field">
    URL de la imagen (Opcional):<br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.check_box :esturistico %>
    <%= label_tag(:esturistico, "Es de interés turístico") %>
  </div>
  Estación del año ideal para su visita
  <div class="field">
<%= f.select(:estacion, options_for_select([['Indiferente', 1], ['Primavera', 2], ['Verano', 3], ['Otoño', 4], ['Invierno', 5]], @comment.estacion), {:include_blank => false}, :class => 'styled-select')%>
  </div>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :zoom %><br />
    <%= f.text_field :zoom %>
  </div>
  <div class="field" style="visibility:hidden;display:none;" >
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field" style="visibility:hidden;display:none;">
    <%= f.label :site_id %><br />
    <%= f.text_field :site_id %>
  </div>

  <div class="actions">
    
    <%= f.submit "Confirmar", :class => 'botonaccion' %>
  </div>
</div>

<div id="col2">
<div id="map_canvas"></div>
<div>
    <input id="address" type="textbox" value="">
    <input type="button" value="Geocode" onclick="codeAddress()">
</div>
</div>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&region=ES"></script>
<script type="text/javascript">
  var geocoder;
  var map;
  var marker;

  function initialize() {
    geocoder = new google.maps.Geocoder();
    
    if(document.getElementById("comment_latitude").value!=0){

    var mylat = document.getElementById("comment_latitude").value; 
    var mylong = document.getElementById("comment_longitude").value;
    var zoom = 12;
    var latlng = new google.maps.LatLng(mylat, mylong);
    var myOptions = {
      zoom: zoom,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }

    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    marker = new google.maps.Marker({
      position: latlng, 
      map: map,
      draggable: true
    });

}else{
    var mylat = 40;
    var mylong = -3;
    var zoom = 5;

    var latlng = new google.maps.LatLng(mylat, mylong);
    var myOptions = {
      zoom: zoom,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }

    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
}
    


 google.maps.event.addListener(map, 'click', function(event) {

    var myLatLng = event.latLng;
    var lat = myLatLng.lat();
    var lng = myLatLng.lng();

    document.getElementById("comment_latitude").value = lat;
    document.getElementById("comment_longitude").value = lng;

    marker = new google.maps.Marker({
      position: event.latLng, 
      map: map,
      draggable: true
    });
 });

  google.maps.event.addListener(marker, 'dragend', function() {
    var myLatLng = marker.getPosition();
    var lat = myLatLng.lat();
    var lng = myLatLng.lng();

    document.getElementById("comment_latitude").value = lat;
    document.getElementById("comment_longitude").value = lng;

  });

  }

  function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

    var myLatLng = results[0].geometry.location;
    var lat = myLatLng.lat();
    var lng = myLatLng.lng();

        document.getElementById("comment_latitude").value = lat;
	document.getElementById("comment_longitude").value = lng;
         marker = new google.maps.Marker({
            map: map, 
            position: results[0].geometry.location,
            draggable: true
        });
      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

</script>

<% end %>
</body>

app/views/comments/edit.html.erb
<h1>Edita el sitio</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @comment %> |
<% if @comment.site_id %>
<%= link_to 'Volver atrás', site_comments_path(@comment.site_id) %>
<% else %>
<%= link_to 'Volver atrás', "javascript:history.back()" %>
<% end %>

app/views/comments/index.html.erb
<div id="site_list"> 
<div id="col1">

<div id="lugares">
<h1>
  <% if @localidad %>
  <% if tipocomentarioconid(@tipo) %>
  <%= link_to @localidad, site_path(params[:site_id]) %> > <%= tipocomentarioconid(@tipo) %>
  <% else %>
  Sitios en <%= link_to @localidad, site_path(params[:site_id]) %>
  <% end %>
  <% else %>
  <%= @titulo %>
  <% end %>
</h1>
</div>
<% if @comments.empty? %>
   <p>Vaya, parece que nadie ha compartido nada. ¡Sé el primero pulsando <%= link_to 'aquí', :controller => "comments", :action => "new", :site_id => params[:site_id], :tipocomentario => params[:tipocomentario ] %>!</p>
<% else %>
  <table> 

  <% @comments.each do |comment| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
  
     <% if comment.image_url.nil? %>
     <% else %>
      <td> 
        <%= link_to image_tag(comment.image_url, :class => 'list_image'), comment if comment.image_url?%>
      </td> 
	<%end %>

      <td class="list_description"> 
        <dl> 
	  <% if comment.user_id %>
          <dt><%= link_to comment.nombre, comment %></dt>            
        </dl> 
      </td> 

 <% if current_user %>
 <% if comment.user_id == current_user.id%>
      <td class="list_actions">  
        <%= link_to 'Editar', edit_comment_path(comment) %><br/> 
        <%= link_to 'Eliminar', comment, 
                    :confirm => '¿Estás seguro?',
                    :method => :delete %>
      </td> 
 <% end %>
 <% end %>
          <% end %>

    </tr> 
  <% end %>
  </table> 

<br />
<%= link_to ' Añade tu sitio ',{ :controller => "comments", :action => "new", :site_id => params[:site_id], :tipocomentario => params[:tipocomentario ]}, :class => "ba2" %>
<br />
<br />
<br />
</div>
<%if @comments_turisticos.empty? %>
<%else %>
<div id="col2">

<h1>Si eres turista no te puedes perder:</h1>
  <table> 
  <% @comments_turisticos.each do |comment| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
  
     <% if comment.image_url.nil? %>
     <% else %>
      <td> 
        <%= link_to image_tag(comment.image_url, :class => 'list_image'), comment if comment.image_url?%>
      </td> 
	<%end %>

      <td class="list_description"> 
        <dl> 
	  <% if comment.user_id %>
          <dt><%= link_to comment.nombre, comment %></dt>            
        </dl> 
      </td> 

 <% if current_user %>
 <% if comment.user_id == current_user.id%>
      <td class="list_actions">  
        <%= link_to 'Editar', edit_comment_path(comment) %><br/> 
        <%= link_to 'Eliminar', comment, 
                    :confirm => '¿Estás seguro?',
                    :method => :delete %>
      </td> 
 <% end %>
 <% end %>
          <% end %>

    </tr> 
  <% end %>
  </table> 
</div>
<%end%>
<%end%>

</div> 

app/views/comments/index.mobile.erb
<div id="site_list"> 
<div id="col1">

<div id="lugares">
<h1>
  <% if @localidad %>
  <% if tipocomentarioconid(@tipo) %>
  <%= link_to @localidad, site_path(params[:site_id]) %> > <%= tipocomentarioconid(@tipo) %>
  <% else %>
  Sitios en <%= link_to @localidad, site_path(params[:site_id]) %>
  <% end %>
  <% else %>
  <%= @titulo %>
  <% end %>
</h1>
</div>
<% if @comments.empty? %>
   <p>Vaya, parece que nadie ha compartido nada. ¡Sé el primero pulsando <%= link_to 'aquí', :controller => "comments", :action => "new", :site_id => params[:site_id], :tipocomentario => params[:tipocomentario ] %>!</p>
<% else %>
  <table> 

  <% @comments.each do |comment| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
  
     <% if comment.image_url.nil? %>
     <% else %>
      <td> 
        <%= link_to image_tag(comment.image_url, :class => 'list_image'), comment if comment.image_url?%>
      </td> 
	<%end %>

      <td class="list_description"> 
        <dl> 
	  <% if comment.user_id %>
          <dt><%= link_to comment.nombre, comment %></dt>            
        </dl> 
      </td> 

 <% if current_user %>
 <% if comment.user_id == current_user.id%>
      <td class="list_actions">  
        <%= link_to 'Editar', edit_comment_path(comment) %><br/> 
        <%= link_to 'Eliminar', comment, 
                    :confirm => '¿Estás seguro?',
                    :method => :delete %>
      </td> 
 <% end %>
 <% end %>
          <% end %>

    </tr> 
  <% end %>
  </table> 


</div>
<%if @comments_turisticos.empty? %>
<%else %>
<div id="col2">

<h1>Si eres turista no te puedes perder:</h1>
  <table> 
  <% @comments_turisticos.each do |comment| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
  
     <% if comment.image_url.nil? %>
     <% else %>
      <td> 
        <%= link_to image_tag(comment.image_url, :class => 'list_image'), comment if comment.image_url?%>
      </td> 
	<%end %>

      <td class="list_description"> 
        <dl> 
	  <% if comment.user_id %>
          <dt><%= link_to comment.nombre, comment %></dt>            
        </dl> 
      </td> 

 <% if current_user %>
 <% if comment.user_id == current_user.id%>
      <td class="list_actions">  
        <%= link_to 'Editar', edit_comment_path(comment) %><br/> 
        <%= link_to 'Eliminar', comment, 
                    :confirm => '¿Estás seguro?',
                    :method => :delete %>
      </td> 
 <% end %>
 <% end %>
          <% end %>

    </tr> 
  <% end %>
  </table> 
</div>
<%end%>
<%end%>

<div id="barra_inferior">
<%= link_to ' Añade tu sitio ',{ :controller => "comments", :action => "new", :site_id => params[:site_id], :tipocomentario => params[:tipocomentario ]}, :class => "ba2" %>
</div>
</div> 

app/views/comments/new.html.erb
<h1>Añade tu sitio a compartir</h1>

<%= render 'form' %>

<script type="text/javascript">
	document.getElementById("comment_zoom").value = 12;
</script>

<div id="despuescol">
<%= link_to 'Volver atrás', "javascript:history.back()" %>
</div>

app/views/comments/show.html.erb
<body id="planet" onload="displayMapa()"> 
<div id="col2">
<div id="map_canvas"></div>
<h2>Datos</h2>

<span>
<b>Latitud:</b>
<%= @comment.latitude %>
</span>

<span>
<b>Longitud:</b>
<%= @comment.longitude %>
</span>
<br/>
Su visita se recomienda en: <%= getestacion(@comment) %>
</div>

<div id="col1">
<div id="lugares">
<p>
<% if current_user %>
<% if @comment.user == current_user %>
<h1>   <%= link_to Site.find(@comment.site_id).name, site_path(@comment.site_id) %> > <%= link_to tipocomentario(@comment), :controller => "comments", :action => "index", :site_id => @comment.site_id, :tipocomentario => @comment.tipocomentario %> > <%= @comment.nombre %> </h1>

<table border="0">
<tr>
<td>
<%= button_to "Editar", edit_comment_path(@comment), {:class => "botonaccion", :method => :get} %>
</td>

<td><%= button_to "Eliminar", @comment, {:class => "botonaccion", :confirm => '¿Estás seguro?', :method => :delete} %>
</td>
</tr>
</table>
<% else %>
<h1>   <%= link_to Site.find(@comment.site_id).name, site_path(@comment.site_id) %> > <%= link_to tipocomentario(@comment), :controller => "comments", :action => "index", :site_id => @comment.site_id, :tipocomentario => @comment.tipocomentario %> > <%= @comment.nombre %></h1>
<% end %>
<% end %>
</p>
</div>

<%= image_tag(@comment.image_url, :class => 'comment_image') if @comment.image_url? %>

<h2>Descripción</h2>
<p>
  <b>Descubierto por:</b>
<% if @user %>
<% nombre = User.find(@comment.user_id).name %>

<%= link_to(nombre, :controller => "users", :action => "show", :id => User.find(@comment.user_id).id) %>, quien comparte con nosotros su experiencia:
<% else %>
Usuario eliminado, quien comparte con nosotros su experiencia:
<% end %>
</p>
<p>
  <%= @comment.comment %>
</p>


</div>
<div id ="despuescol">
<h2> Opiniones </h2>
<%= render :partial => "respuesta/respuesta",
           :collection => @comment.respuesta %>

<a href="#" id="mostrar">Añada su opinión</a>  
<div id="caja">  
<%= render "respuesta/form2" %>
</div>  
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">

function displayMapa() {

	var mylat = <%= @comment.latitude %>
	var mylong = <%= @comment.longitude %>

	var latlng = new google.maps.LatLng(mylat, mylong);

	var myOptions = {
			zoom:     <%= @comment.zoom %>, 
			center: latlng, 
			mapTypeId: google.maps.MapTypeId.ROADMAP 
	};

	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);


	var marker = new google.maps.Marker({
		position: latlng,
		map: map
	});

}

</script>
</body>

app/views/comments/show.mobile.erb
<body id="planet" onload="displayMapa()"> 
<div id="col2">
<div id="map_canvas"></div>
<h2>Datos</h2>

<span>
<b>Latitud:</b>
<%= @comment.latitude %>
</span>

<span>
<b>Longitud:</b>
<%= @comment.longitude %>
</span>
<br/>
Su visita se recomienda en: <%= getestacion(@comment) %>
</div>

<div id="col1">
<div id="lugares">
<p>
<% if current_user %>
<% if @comment.user == current_user %>
<h1>   <%= link_to Site.find(@comment.site_id).name, site_path(@comment.site_id) %> > <%= link_to tipocomentario(@comment), :controller => "comments", :action => "index", :site_id => @comment.site_id, :tipocomentario => @comment.tipocomentario %> > <%= @comment.nombre %> </h1>

<table border="0">
<tr>
<td>
<%= button_to "Editar", edit_comment_path(@comment), {:class => "botonaccion", :method => :get} %>
</td>

<td><%= button_to "Eliminar", @comment, {:class => "botonaccion", :confirm => '¿Estás seguro?', :method => :delete} %>
</td>
</tr>
</table>
<% else %>
<h1>   <%= link_to Site.find(@comment.site_id).name, site_path(@comment.site_id) %> > <%= link_to tipocomentario(@comment), :controller => "comments", :action => "index", :site_id => @comment.site_id, :tipocomentario => @comment.tipocomentario %> > <%= @comment.nombre %></h1>
<% end %>
<% end %>
</p>
</div>

<%= image_tag(@comment.image_url, :class => 'comment_image') if @comment.image_url? %>

<h2>Descripción</h2>
<p>
  <b>Descubierto por:</b>
<% if @user %>
<% nombre = User.find(@comment.user_id).name %>

<%= link_to(nombre, :controller => "users", :action => "show", :id => User.find(@comment.user_id).id) %>, quien comparte con nosotros su experiencia:
<% else %>
Usuario eliminado, quien comparte con nosotros su experiencia:
<% end %>
</p>
<p>
  <%= @comment.comment %>
</p>


</div>
<div id ="despuescol">
<h2> Opiniones </h2>
<%= render :partial => "respuesta/respuesta",
           :collection => @comment.respuesta %>

<a href="#" id="mostrar">Añada su opinión</a>  
<div id="caja">  
<%= render "respuesta/form2" %>
</div>  
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">

function displayMapa() {

	var mylat = <%= @comment.latitude %>
	var mylong = <%= @comment.longitude %>

	var latlng = new google.maps.LatLng(mylat, mylong);

	var myOptions = {
			zoom:     <%= @comment.zoom %>, 
			center: latlng, 
			mapTypeId: google.maps.MapTypeId.ROADMAP 
	};

	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);


	var marker = new google.maps.Marker({
		position: latlng,
		map: map
	});

}

</script>
</body>