config/routes.rb
Planet::Application.routes.draw do

  root :to => "planet#index"

  devise_for :users
  resources :users, :only => [:index, :show]

  resources :typecomentarios
  
  resources :comments

  resources :sites do
       collection do
          get 'search'
       end
   end

  resources :sites do
	member do
	get 'like'
	end
  end

  resources :respuesta do
	member do
	get 'like'
	end
  end

  resources :types do
      resources :sites
  end

  resources :sites do
      resources :comments
  end

  resources :comments do
      resources :respuesta
  end
  resources :sites
  resources :respuesta

  get "planet/index"
  get "planet/explorar"
  get "planet/contacto"
  get "planet/acercade"
  get "planet/terminos"
  get "planet/privacidad"

end

app/controllers/types_controller.rb
class TypesController < ApplicationController


def check_mobile
  request.format = :html

end

  # GET /types
  # GET /types.xml
  def index
    @types = Type.all(:order => :name)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @types }
    end
  end

  # GET /types/1
  # GET /types/1.xml
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/new
  # GET /types/new.xml
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.xml
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to(types_path, :notice => 'Nueva provincia creada.') }
        format.xml  { render :xml => @type, :status => :created, :location => @type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.xml
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to(types_path, :notice => 'Provincia actualizada correctamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.xml
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to(types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Nombre:<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Descripción (opcional):<br />
    <%= f.text_area :description, :rows => 4 %>
  </div>
  <div class="actions">
    <%= f.submit "Confirmar", :class => 'botonaccion' %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html (copia).erb
<div id="site_list"> 
  <h1>Provincias</h1> 
 
  <table> 
  <% @types.each do |type| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to type.name, 'types/'+type.id.to_s+'/sites' %></dt> 
          <dd><%= truncate(strip_tags(type.description),
                 :length => 80) %></dd> 
        </dl> 
      </td> 
 
      <td class="list_actions"> 
        <%= link_to 'Show', type %><br/> 
        <%= link_to 'Edit', edit_type_path(type) %><br/> 
        <%= link_to 'Destroy', type, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 

<br />

<%= link_to 'Añade tu provincia', new_type_path %>

app/views/types/index.html.erb
  <h1>Provincias</h1> 
 
  <% @types.each do |type| %>
<div id="provincias">
          <dt><%= link_to type.name, 'types/'+type.id.to_s+'/sites' %></dt> 
</div>
  <% end %>

<br />
<div id="provincias_añade">

<%= link_to 'Añade tu provincia', new_type_path %>
</div>

app/views/types/index.mobile.erb
  <h1>Provincias</h1> 
 
  <% @types.each do |type| %>
<div id="provincias">
          <dt><%= link_to type.name, 'types/'+type.id.to_s+'/sites' %></dt> 
</div>
  <% end %>

<br />
<div id="provincias_añade">

<%= link_to 'Añade tu provincia', new_type_path %>
</div>

app/views/types/new.html.erb
<h1>Nueva provincia</h1>

<%= render 'form' %>

<div id="despuescol">
<%= link_to '< Volver atrás', types_path %>
</diV>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @type.description %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>