config/routes.rb
Planet::Application.routes.draw do

  root :to => "planet#index"

  devise_for :users
  resources :users, :only => [:index, :show]

  resources :typecomentarios
  
  resources :comments

  resources :sites do
       collection do
          get 'search'
       end
   end

  resources :sites do
	member do
	get 'like'
	end
  end

  resources :respuesta do
	member do
	get 'like'
	end
  end

  resources :types do
      resources :sites
  end

  resources :sites do
      resources :comments
  end

  resources :comments do
      resources :respuesta
  end
  resources :sites
  resources :respuesta

  get "planet/index"
  get "planet/explorar"
  get "planet/contacto"
  get "planet/acercade"
  get "planet/terminos"
  get "planet/privacidad"

end

app/models/site.rb
class Site < ActiveRecord::Base

   belongs_to :type
   belongs_to :user

  validate do |site|
    site.errors.add_to_base("El nombre no puede estar vacio") if site.name.blank?
  end
   validates :type_id, :latitude, :longitude, :zoom, :tipositio, :presence => true
   validates :zoom, :numericality => {:greater_than_or_equal_to => 0.1}
   validates_uniqueness_of :name, :case_sensitive => false

   # Prevents the assignation of sites to other users
   attr_protected :user_id

   has_many :comments

   make_flaggable :estado
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index, :show, :search]
  load_and_authorize_resource

  after_filter :count_visit, :only => :show   
  after_filter :baja_karma, :only => :destroy

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to(root_url, :notice => 'Permiso denegado.')
  end

  def like
	@site = Site.find(params[:id])  
	if @current_user.flagged?(@site, :estado)
		@current_user.unflag(@site, :estado)
		msg = "No has estado aqui."
	else
		@current_user.flag(@site, :estado)
		msg = "Has estado aqui."
	end
	redirect_to @site, :notice => msg
  end

  # GET /sites
  # GET /sites.xml
  def index
 
   if params[:type_id].nil? or params[:type_id].empty? and !params[:tipositio].nil?
      @sites = Site.where(:tipositio => params[:tipositio])
      @tipo = params[:tipositio]
   elsif params[:tipositio].nil? or params[:tipositio].empty? and !params[:type_id].nil?
      @sites = Type.find(params[:type_id]).sites
      @provincia = Type.find(params[:type_id]).name
   elsif !params[:type_id].nil?  and !params[:tipositio].nil?
      @sites = Site.where(:tipositio => params[:tipositio], :type_id => params[:type_id])
      @provincia = Type.find(params[:type_id]).name
   elsif !params[:user_id].nil?
      @sites = Site.where(:user_id => params[:user_id])
   elsif params[:type_id].nil? and params[:tipositio].nil? 
      @sites = Site.all
   else
      @sites = Site.where(:tipositio => params[:tipositio], :type_id => params[:type_id])
      @provincia = Type.find(params[:type_id]).name
      @tipo = params[:tipositio]
   end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])
    @user = User.find_by_id(@site.user_id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new

   if params[:type_id] and params[:tipositio]
      @site.type_id = params[:type_id]
      @site.tipositio = params[:tipositio]
      @site.user = current_user
   elsif params[:type_id]
      @site.type_id = params[:type_id]
      @site.user = current_user
   elsif params[:tipositio]
      @site.tipositio = params[:tipositio]
      @site.user = current_user
   else
      @site.user = current_user
   end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site.user = current_user

    respond_to do |format|
      if @site.save
        sube_karma
        format.html { redirect_to(@site, :notice => 'Nueva localidad creada.') }
        format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to(@site, :notice => 'Localidad actualizada correctamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.xml  { head :ok }
    end
  end

   def search 
     str=params[:q]
     @sites = Site.where("LOWER (name) LIKE ? OR LOWER (description) LIKE ?", "%#{str.downcase}%", "%#{str.downcase}%")
   end

  private

  def count_visit
    @site.increment!(:visits)
  end

  def sube_karma
    @user = User.find(@site.user_id)
    @user.increment!(:karma)
  end

  def baja_karma
    @user = User.find(@site.user_id)
    @user.decrement!(:karma)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
 def tipositio(site)
 	tipo = case site.tipositio
	 	when 2 then "Ciudad"
	 	when 3 then "Rural"
	 	when 4 then "Playa"
 	end

	return tipo
 end

 def tipositio(tipo)
 	tipo = case tipo.to_s
	 	when 2 then "urbanas"
	 	when 3 then "rurales"
	 	when 4 then "de playa"
	end 

	return tipo
 end

 def toggle_heestado_button(site, user)
	if user.flagged?(site, :estado)
		link_to "No conozco este sitio", like_site_path(site), :class => "ba2"
	else
		link_to "Conozco este sitio", like_site_path(site), :class => "ba2"
	end
 end
end

app/views/sites/_form.html (copia).erb
<body id="planet" onload="initialize()"> 
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="container2">
<div id="container1">

<div id="col1">

  Provincia a la que pertenece: <br/>
  <div class="field">
    <% types = Type.find(:all, :order => :name) %>

<%= collection_select(:site, :type_id, types, :id, :name, {:prompt=>false}, {:class=>'styled-select'}) %>
  </div>
  Tipo de turismo: <br />
  <div class="field">
<%= f.select(:tipositio, options_for_select([['Ciudad', 2], ['Rural', 3], ['Playa', 4]], @site.tipositio), {:include_blank => false}, :class => 'styled-select')%>
  </div>
  <div class="field">
    Nombre de la localidad:<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Descripción (Opcional):<br />
    <%= f.text_area :description, :rows => 4 %>
  </div>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.field :zoom %><br />
    <%= f.text_field :zoom %>
  </div>
  <div class="field">
    URL de la imagen (Opcional):<br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit "Confirmar", :class => 'botonaccion' %>
  </div>
</div>
<div id="col2">
<div id="map_canvas"></div>
<div>
    <input id="address" type="textbox" value="">
    <input type="button" value="Geocode" onclick="codeAddress()">
</div>
</div>

</div>
</div>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&region=ES"></script>
<script type="text/javascript">
  var geocoder;
  var map;
  var marker;

  function initialize() {
    geocoder = new google.maps.Geocoder();
    
    if(document.getElementById("site_latitude").value!=0){

    var mylat = document.getElementById("site_latitude").value; 
    var mylong = document.getElementById("site_longitude").value;
    var zoom = 12;
    var latlng = new google.maps.LatLng(mylat, mylong);
    var myOptions = {
      zoom: zoom,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }

    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    marker = new google.maps.Marker({
      position: latlng, 
      map: map,
      draggable: true
    });

}else{
    var mylat = 40;
    var mylong = -3;
    var zoom = 5;

    var latlng = new google.maps.LatLng(mylat, mylong);
    var myOptions = {
      zoom: zoom,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }

    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
}
    


 google.maps.event.addListener(map, 'click', function(event) {

    var myLatLng = event.latLng;
    var lat = myLatLng.lat();
    var lng = myLatLng.lng();

    document.getElementById("site_latitude").value = lat;
    document.getElementById("site_longitude").value = lng;

    marker = new google.maps.Marker({
      position: event.latLng, 
      map: map,
      draggable: true
    });
 });

  google.maps.event.addListener(marker, 'dragend', function() {
    var myLatLng = marker.getPosition();
    var lat = myLatLng.lat();
    var lng = myLatLng.lng();

    document.getElementById("site_latitude").value = lat;
    document.getElementById("site_longitude").value = lng;

  });

  }

  function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);

    var myLatLng = results[0].geometry.location;
    var lat = myLatLng.lat();
    var lng = myLatLng.lng();

        document.getElementById("site_latitude").value = lat;
	document.getElementById("site_longitude").value = lng;
         marker = new google.maps.Marker({
            map: map, 
            position: results[0].geometry.location,
            draggable: true
        });
      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

</script>

<% end %>
</body>

app/views/sites/_localidades.html.erb
<div id="site_list"> 
  <h1>Localidades más populares</h1> 
  <% @sites = Site.find(:all, :order => 'visits DESC', :limit => '5') %>
  <table> 
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td> 
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site if  site.image_url? %>
      </td> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to site.name, site %></dt> 
          <dd><%= truncate(strip_tags(site.description),
                 :length => 40) %></dd>
        </dl> 
      </td>
 
      <td class="list_actions"> 
	<% if current_user %>
        <% if site.user == current_user %>
          <%= link_to 'Editar', edit_site_path(site) %><br/>
          <%= link_to 'Eliminar', site, 
                      :confirm => '¿Estás seguro?',
                      :method => :delete %>
        <% end %>
        <% end %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 

app/views/sites/edit.html.erb
<h1>Edita la localidad</h1>

<%= render 'form' %>

<div id="despuescol">
<%= link_to '< Volver atrás', @site %>
</div>

app/views/sites/edit.mobile.erb
<h1>Edita la localidad</h1>

<%= render 'form' %>

<div id="despuescol">
<%= link_to '< Volver atrás', @site %>
</div>

app/views/sites/index.html.erb
<div id="site_list">
  <% if @provincia %> 
  <h1>Localidades en <%= @provincia %></h1> 
Filtros: <%= link_to('Playa', :controller => "sites", :action => "index", :tipositio => 4, :type_id => params[:type_id]) %>, <%= link_to('Ciudad', :controller => "sites", :action => "index", :tipositio => 2, :type_id => params[:type_id]) %> o <%= link_to('Rural', :controller => "sites", :action => "index", :tipositio => 3, :type_id => params[:type_id]) %>
<br />
<br />
  <% elsif @tipo %>
  <h1>Localidades <%= tipositio(@tipo) %></h1>  
  <% else %>
  <h1>Localidadess <%= @tipo %></h1> 
<% end %> 
<%= link_to ' Añade una nueva localidad ',{ :controller => "sites", :action => "new", :type_id => params[:type_id], :tipositio => params[:tipositio]}, :class => "ba2" %>
</br>
</br>
  <table> 
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td> 
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site if site.image_url?%>
      </td> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to site.name, site %></dt> 
          <dd><%= truncate(strip_tags(site.description),
                 :length => 40) %></dd>
        </dl> 
      </td>
 
      <td class="list_actions"> 
 <% if current_user %>
        <% if site.user == current_user %>
          <%= link_to 'Editar', edit_site_path(site) %><br/>
          <%= link_to 'Eliminar', site, 
                      :confirm => '¿Estás seguro?',
                      :method => :delete %>
        <% end %>
        <% end %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 
 
<br /> 

app/views/sites/index.mobile.erb
<div id="site_list">
  <% if @provincia %> 
  <h1>Localidades en <%= @provincia %></h1> 
Filtros: <%= link_to('Playa', :controller => "sites", :action => "index", :tipositio => 4, :type_id => params[:type_id]) %>, <%= link_to('Ciudad', :controller => "sites", :action => "index", :tipositio => 2, :type_id => params[:type_id]) %> o <%= link_to('Rural', :controller => "sites", :action => "index", :tipositio => 3, :type_id => params[:type_id]) %>
<br />
<br />
  <% elsif @tipo %>
  <h1>Localidades <%= tipositio(@tipo) %></h1>  
  <% else %>
  <h1>Localidadess <%= @tipo %></h1> 
<% end %> 
  <table> 
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td> 
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site if site.image_url?%>
      </td> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to site.name, site %></dt> 
          <dd><%= truncate(strip_tags(site.description),
                 :length => 40) %></dd>
        </dl> 
      </td>
 
      <td class="list_actions"> 
 <% if current_user %>
        <% if site.user == current_user %>
          <%= link_to 'Editar', edit_site_path(site) %><br/>
          <%= link_to 'Eliminar', site, 
                      :confirm => '¿Estás seguro?',
                      :method => :delete %>
        <% end %>
        <% end %>
      </td> 
    </tr> 
  <% end %>
  </table>

<br /> 

<div id="barra_inferior">
<%= link_to ' Añade una nueva localidad ',{ :controller => "sites", :action => "new", :type_id => params[:type_id], :tipositio => params[:tipositio]}, :class => "ba2" %> 
</div>
</div> 
 
<br /> 

app/views/sites/new.html.erb
<h1>Añade tu localidad</h1>

<%= render 'form' %>

<script type="text/javascript">
	document.getElementById("site_zoom").value = 12;
</script>

<div id="despuescol">
<%= link_to '< Volver atrás', sites_path %>
</diV>

app/views/sites/new.mobile.erb
<h1>Añade tu localidad</h1>

<%= render 'form' %>

<script type="text/javascript">
	document.getElementById("site_zoom").value = 12;
</script>

<div id="despuescol">
<%= link_to '< Volver atrás', sites_path %>
</diV>

app/views/sites/search.html.erb
<% if @sites.nil? %>
<p>Lo sentimos, no se ha encontrado nada.</p>
<% else %>
<div id="site_list"> 
  <h1>Listing Sites</h1> 
 
  <table> 
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td> 
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site %>
      </td> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to site.name, site %></dt> 
          <dd><%= truncate(strip_tags(site.description),
                 :length => 80) %></dd>
        </dl> 
      </td>
 
      <td class="list_actions"> 
        <%= link_to 'Show', site %><br/>
        <%= link_to 'Edit', edit_site_path(site) %><br/>
        <%= link_to 'Destroy', site, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 
 
<br /> 
 
<%= link_to 'New site', new_site_path %>
<% end %>

app/views/sites/search.mobile.erb
<% if @sites.nil? %>
<p>Lo sentimos, no se ha encontrado nada.</p>
<% else %>
<div id="site_list"> 
  <h1>Listing Sites</h1> 
 
  <table> 
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td> 
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site %>
      </td> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to site.name, site %></dt> 
          <dd><%= truncate(strip_tags(site.description),
                 :length => 80) %></dd>
        </dl> 
      </td>
 
      <td class="list_actions"> 
        <%= link_to 'Show', site %><br/>
        <%= link_to 'Edit', edit_site_path(site) %><br/>
        <%= link_to 'Destroy', site, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 
 
<br /> 
 
<%= link_to 'New site', new_site_path %>
<% end %>

app/views/sites/show.html.erb
<body id="planet" onload="displayMapa()"> 
<div id="site">

<div id="col2">
<div id="map_canvas"></div>
<h2>Datos</h2>

<span>

<b>Descubierto por:</b>

<% if @user %>
<% nombre = User.find(@site.user_id).name %>

<%= link_to(nombre, :controller => "users", :action => "show", :id => User.find(@site.user_id).id) %>
<% else %>
Usuario eliminado
<% end %>

</span>

<span>
<b>Tipo de turismo: </b>
<%= link_to(tipositio(@site), :controller => "sites", :action => "index", :tipositio => @site.tipositio) %>
</span>
<br />

<span>
<b>Latitud:</b>
<%= @site.latitude %>
</span>

<span>
<b>Longitud:</b>
<%= @site.longitude %>
</span>

<br/>

<b>Visitas:</b>
<%= @site.visits %>

<br/>
<br/>
<% if @current_user %>
<div id="site_list">
<div id="ba2">
<%= toggle_heestado_button(@site, @current_user) %>
</div>
</div>
<% end %>
</div>

<div id="lugares">
<div id="col1">
<h1><%= link_to @site.type.name, '../types/'+@site.type_id.to_s+'/sites' %> > <%= @site.name %></h1> 
<% if current_user %>
<% if @site.user == current_user %>

<table border="0">
<tr>
<td>
<%= button_to "Editar", edit_site_path(@site), {:class => "botonaccion", :method => :get} %>
</td>

<td><%= button_to "Eliminar", @site, {:class => "botonaccion", :confirm => '¿Estás seguro?', :method => :delete} %>
</td>
</tr>
</table>

<% else %>

<% end %>
<% end %>

<%= image_tag(@site.image_url, :class => 'site_image') if @site.image_url? %>

<p><h2>Descubre <%= @site.name %></h2></p>
 	<p><b><%= link_to('Sitios que ver', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 2) %></b> | 
 	<b><%= link_to('Monumentos', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 3) %></b> |
 	<b><%= link_to('Museos', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 4) %></b> | 
        <b><%= link_to('Parques', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 9) %></b></p> 
 	<p><b><%= link_to('Hoteles', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 5) %></b> |
 	<b><%= link_to('Casas rurales', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 6) %></b> |
 	<b><%= link_to('Sitios donde comer', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 7) %></b> |
 	<b><%= link_to('De compras', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 8) %></b></p>
        <p>Información útil: <b><%= link_to('Transporte', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 10) %></b></p>
        <p><b><%= link_to('Ver todo', :controller => "comments", :action => "index", :site_id => @site.id) %></b></p>
</div> 

<div id="despuescol">
<% if @site.description.present? %>
<h2>Descripción</h2> 
<p><%=@site.description %></p>
<% end %>


</div>
</div>
</div>


<script type="text/javascript">

function displayMapa() {

	var mylat = <%= @site.latitude %>
	var mylong = <%= @site.longitude %>

	var latlng = new google.maps.LatLng(mylat, mylong);

	var myOptions = {
			zoom:     <%= @site.zoom %>, 
			center: latlng, 
			mapTypeId: google.maps.MapTypeId.ROADMAP 
	};

	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);


	var marker = new google.maps.Marker({
		position: latlng,
		map: map,
		title: " <%= @site.name.to_s %>  "
	});

}

</script>
</body>

app/views/sites/show.mobile.erb
<body id="planet" onload="displayMapa()"> 
<div id="site">

<div id="lugares">
<h1><%= link_to @site.type.name, '../types/'+@site.type_id.to_s+'/sites' %> > <%= @site.name %></h1> 
<% if current_user %>
<% if @site.user == current_user %>

<table border="0">
<tr>
<td>
<%= button_to "Editar", edit_site_path(@site), {:class => "botonaccion", :method => :get} %>
</td>

<td><%= button_to "Eliminar", @site, {:class => "botonaccion", :confirm => '¿Estás seguro?', :method => :delete} %>
</td>
</tr>
</table>

<% else %>

<% end %>
<% end %>

<%= image_tag(@site.image_url, :class => 'site_image') if @site.image_url? %>

<h2>Datos</h2>

<span>

<b>Descubierto por:</b>

<% if @user %>
<% nombre = User.find(@site.user_id).name %>

<%= link_to(nombre, :controller => "users", :action => "show", :id => User.find(@site.user_id).id) %>
<% else %>
Usuario eliminado
<% end %>

</span>

<span>
<b>Tipo de turismo: </b>
<%= link_to(tipositio(@site), :controller => "sites", :action => "index", :tipositio => @site.tipositio) %>
</span>
<br />

<span>
<b>Latitud:</b>
<%= @site.latitude %>
</span>

<span>
<b>Longitud:</b>
<%= @site.longitude %>
</span>

<br/>

<span>
<b>Visitas:</b>
<%= @site.visits %>
</span>
<br/>

<p><h2>Descubre <%= @site.name %></h2></p>
 	<p><b><%= link_to('Sitios que ver', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 2) %></b> | 
 	<b><%= link_to('Monumentos', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 3) %></b> |
 	<b><%= link_to('Museos', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 4) %></b> | 
        <b><%= link_to('Parques', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 9) %></b></p> 
 	<p><b><%= link_to('Hoteles', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 5) %></b> |
 	<b><%= link_to('Casas rurales', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 6) %></b> |
 	<b><%= link_to('Sitios donde comer', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 7) %></b> |
 	<b><%= link_to('De compras', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 8) %></b></p>
        <p>Información útil: <b><%= link_to('Transporte', :controller => "comments", :action => "index", :site_id => @site.id, :tipocomentario => 10) %></b></p>
        <p><b><%= link_to('Ver todo', :controller => "comments", :action => "index", :site_id => @site.id) %></b></p>

<% if @site.description.present? %>
<h2>Descripción</h2> 
<p><%=@site.description %></p>
<% end %>

<div id="map_canvas"></div>



</div>
</div>

<div id="barra_inferior">
<% if @current_user %>
<div id="site_list">
<div id="ba2">
<%= toggle_heestado_button(@site, @current_user) %>
</div>
</div>
<% end %>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">

function displayMapa() {

	var mylat = <%= @site.latitude %>
	var mylong = <%= @site.longitude %>

	var latlng = new google.maps.LatLng(mylat, mylong);

	var myOptions = {
			zoom:     <%= @site.zoom %>, 
			center: latlng, 
			mapTypeId: google.maps.MapTypeId.ROADMAP 
	};

	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);


	var marker = new google.maps.Marker({
		position: latlng,
		map: map,
		title: " <%= @site.name.to_s %>  "
	});

}

</script>
</body>