config/routes.rb
Planet::Application.routes.draw do

  root :to => "planet#index"

  devise_for :users
  resources :users, :only => [:index, :show]

  resources :typecomentarios
  
  resources :comments

  resources :sites do
       collection do
          get 'search'
       end
   end

  resources :sites do
	member do
	get 'like'
	end
  end

  resources :respuesta do
	member do
	get 'like'
	end
  end

  resources :types do
      resources :sites
  end

  resources :sites do
      resources :comments
  end

  resources :comments do
      resources :respuesta
  end
  resources :sites
  resources :respuesta

  get "planet/index"
  get "planet/explorar"
  get "planet/contacto"
  get "planet/acercade"
  get "planet/terminos"
  get "planet/privacidad"

end

app/views/layouts/application.html (copia).erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>Planet Travel Site</title> 
<!-- START:stylesheet --> 
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "planet", :media => "all" %><!-- <label id="code.slt"/> --> 
<!-- END:stylesheet --> 
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> --> 
<script type="text/javascript"
src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js">
</script>
<script language="javascript" type="text/javascript">
    $j = jQuery.noConflict();
</script>
</head> 
<body> 
  <div id="banner"> 
    <%= image_tag("logo3.png") %>
    <%= @page_title || "Planet Travel Site" %><!-- <label id="code.depot.e.title"/> --> 

    <div class="user">
      <% if current_user %>
        <%= link_to current_user.name, 
               edit_user_registration_path %> |
        <%= link_to "Sign out", 
               destroy_user_session_path %>
      <% else %>
        <%= link_to "Sign in", 
               new_user_session_path %>
      <% end %>
    </div>
  </div> 
  <div id="columns"> 
    <div id="side"> 
      <%= link_to "Home", planet_index_path %><br /> 
      <%= link_to "Tipos",  types_path %><br /> 
      <%= link_to "Sitios", sites_path %><br /> 
      <%= link_to "Contact", planet_contact_path %><br />
      <%= link_to "Sign in", new_session_path(:user) %>
    </div> 
    <div id="main"> 

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %><!-- <label id="code.depot.e.include"/> --> 
    </div> 
  </div> 
</body> 
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>Escapaditas.com</title> 
<!-- START:stylesheet --> 
        <!-- carga de las hojas de estilo -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "planet", :media => "all", :title => "web" %><!-- <label id="code.slt"/> --> 
  <%= stylesheet_link_tag "movil", :media => "all", :title => "movil" %><!-- <label id="code.slt"/> --> 

<%= javascript_include_tag'jquery.min.js', 'jquery_ujs.js', 'styleswitcher.js' %>


<script type="text/javascript">
var mobile = (/iphone|ipad|ipod|android|blackberry|mini|windows\sce|palm/i.test(navigator.userAgent.toLowerCase())); 

if (mobile)
{
 $nombre = 'movil';
}
else
{
  $nombre = 'web';
}

 setActiveStyleSheet($nombre); return false;

</script>
<!-- END:stylesheet --> 


<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&region=ES"></script>

<%= csrf_meta_tag %>

<script type="text/javascript"> 
$(function()
{
 
$("#mostrar").click(function(event) {
event.preventDefault();
$("#caja").slideToggle();
});
 
$("#caja a").click(function(event) {
event.preventDefault();
$("#caja").slideUp();
});
});
</script> 
</head> 

<body id="planet"> 

      <script src="../javascripts/modernizr.custom.80028.js"></script>
      <div id="notice">

      <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

      <% if notice %>
	<%= notice %> 
	<a id="close">[close]</a> 
      <% end %>
      </div>
	<script>
	   $("#close").click(function() {
	     $("#notice").hide();
	   });
  	</script>

  <div id="banner">
<%= link_to "escapaditas.com", planet_index_path %><!-- <label id="code.depot.e.title"/> --> 
<div class="subtitulo">
donde comienzan tus planes
</div>

  </div> 
    <div id="barra"> 
      <%= link_to "Inicio", root_path %>
      <%= link_to "Explorar",  planet_explorar_path %>
      <%= link_to "Provincias",  types_path %>
      <%= link_to "Contacto", planet_contacto_path %>
      <a href="#" onclick="setActiveStyleSheet('movil'); return false;">movil</a>
      <a href="#" onclick="setActiveStyleSheet('web'); return false;">web</a>

    <div class="user">
      <% if current_user %>
        <%= link_to current_user.name, 
               edit_user_registration_path %> |
        <%= link_to "Cerrar sesión", 
               destroy_user_session_path %>
       <% if current_user.role.to_s == 666.to_s %>
	Eres Admin
 	<% end %>
      <% else %>
        <%= link_to "Iniciar sesión", 
               new_user_session_path %>
      <% end %>
    </div>
    </div> 


    <% if(request.request_uri != planet_index_path && request.request_uri != root_path) %>
    <div id="busqueda">
      <%= form_tag(search_sites_path, :method => "get", :class => "btn") do %>
      <%= text_field_tag :q, nil, :placeholder => 'Busca cualquier lugar', :size => 25 %>
      <%= image_submit_tag("search2.png") %>
      <% end %>
    </div> 
    <% end %>
    
    <div id="main"> 

<% if(request.request_uri == planet_index_path || request.request_uri == root_path) %>
      <% if !current_user %>
<div id="col1">
<div id="registrate">
<br />
<h1>¿Qué es esto?</h1>
<li>Escapaditas.com es una nueva red social en la que los usuarios comparten sus experiencias con otros con el fin de convertirse en lugar de referencia para todos aquellos que buscan información sobre su próximo viaje o simplemente buscan planes interesantes en su ciudad.</li>
<li>Es muy sencillo de usar, ¿por qué no empiezas ahora? Regístrate, explora nuevos sitios, planes y... ¡Comparte!</li>
<h1>
<%= button_to "Crear una cuenta", new_registration_path(:user), {:class => "minimal", :method => :get} %>
</h1>
</div>
</div>

<div id="col2">
<div id="registrate">
<br />
<h1>Pasos a seguir</h1>
<div class="listacosas">
<li>1. Créate una cuenta, ¡es totalmente gratuito!</li>
<li>2. Descubre nuevos rincones que querrás visitar, nuevos planes que hacer en tu ciudad, obtén más información sobre tu próximo viaje...</li>
<li>3. ¡Y no te olvides de compartir tus experiencias para ayudar a otros!</li>
</div>

</div>
</div>
<% end %>
<% end %>

<div id="main_contenido">

      <%= yield %><!-- <label id="code.depot.e.include"/> --> 

</div>
    </div> 

    <div id="pie"> 
	<div class="texto">
		 <%= link_to "Acerca de...", planet_acercade_path %> <%= link_to "Términos", planet_terminos_path %> <%= link_to "Privacidad", planet_privacidad_path %>
	</div>
    </div> 

</body> 
</html> 

app/views/layouts/application.mobile.erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>Escapaditas.com</title> 
<!-- START:stylesheet --> 
        <!-- carga de las hojas de estilo -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "movil", :media => "all", :title => "movil" %><!-- <label id="code.slt"/> --> 

<%= javascript_include_tag 'jquery.min.js', 'jquery_ujs.js' %>

<!-- END:stylesheet --> 

<%= csrf_meta_tag %>
<meta name = "viewport" content = "width = device-width">


</head> 

<body id="planet"> 

    <div id="barra"> 
      <%= link_to "Inicio", root_path %>
      <%= link_to "Explorar",  planet_explorar_path %>
      <%= link_to "Provincias",  types_path %>
        <%= link_to "Identifícate", 
               new_user_session_path %>
    </div>

    <div id="main"> 


<div id="main_contenido">

      <%= yield %><!-- <label id="code.depot.e.include"/> --> 

</div>
    </div> 


</body> 
</html> 